---
services:
  # Docker container for the web application
  web:
    build: .
    container_name: <container_name>.web
    volumes: 
      - ./app:/var/www/html/app # This is where site files will be stored.
    networks:
      - appnet

  # Docker container for nginx web server.
  nginx:
    image: nginx:alpine
    container_name: <container_name>.nginx
    ports:
      - "80:80" # Change port as required
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro # This is where the nginx configuration file will be stored.
      - ./app:/var/www/html/app # This allows nginx to access stored web files.
    depends_on:
      - web
    networks:
      - appnet

  # Docker container for MySQL database
  db:
    image: mariadb:10.6
    container_name: <container_name>.mariadb
    environment:
      MYSQL_ROOT_PASSWORD: <MYSQL ROOT PASSWORD> # Change as required
      MYSQL_DATABASE: <MYSQL_DATABASE> # Change as required
      MYSQL_USER: <MYSQL_USER_NAME> # Change as required
      MYSQL_PASSWORD: <MYSQL_USER_PASSWORD> # Change as required
    volumes:
      - ./mariadb:/var/lib/mysql # This is where MariaDB datebase files will be stored.
    networks:
      - appnet

#Docker container for PHPMyAdmin database manager.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: <container_name>.phpmyadmin
    ports:
      - "81:80" # Change port as required
    environment:
      PMA_HOST: db
      PMA_ARBIRARY: 1
    depends_on:
      - db
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
